#!/bin/sh
cd fleet-ui
npm run-script build
cd ..
cp fleet-ui/dist/static/css/* public
cp fleet-ui/dist/static/js/* public
if ls fleet-ui/dist/static/js/app*js 1> /dev/null 2>&1; then
  for file in fleet-ui/dist/static/js/app*js; do
    sed -i "s/app.*js/${file##*/}/g" rp.ly.html
  done
fi
if ls fleet-ui/dist/static/js/vendor*js 1> /dev/null 2>&1; then
  for file in fleet-ui/dist/static/js/vendor*js; do
    sed -i "s/vendor.*js/${file##*/}/g" rp.ly.html
  done
fi
if ls fleet-ui/dist/static/js/manifest*js 1> /dev/null 2>&1; then
  for file in fleet-ui/dist/static/js/manifest*js; do
    sed -i "s/manifest.*js/${file##*/}/g" rp.ly.html
  done
fi
if ls fleet-ui/dist/static/css/app*css 1> /dev/null 2>&1; then
  for file in fleet-ui/dist/static/css/*css; do
    sed -i "s/app.*css/${file##*/}/g" rp.ly.html
  done
fi